### ISSUE TITLE
Question about feature values

### ISSUE THREAD

**Issue by mikemcka** [PolusAI/nyxus#228]
Hi there,

I have a few questions about the results I got when using this tool to extract features from a cellular marker intensity dataset.

1. I have quite a few cells that have 0 or nan values for multiple features, is this beacause there is no intensity value at this location? This is expected as the majority of cells in the image are negative for the marker I am looking at.
2. I got values for many features for cells that are supposed to be negative. Is this due to background intensity for these cells? Does this sound normal? 
3. I had a few features such as GABOR return no values or inf for any of my cells, I understand GABOR extractsfeatures at different orientations but just wondering if you had any idea why the feature returned no values for any cells?

Otherwise I am very happy with the package, thankyou very much for devloping it.

Cheers,

Mike

**Comment by sameeul** [comment]
Hi Mike, would it be possible to share one pair of test data so that we can take a look on our end? What is the data type for the images that you are analyzing?

**Comment by mikemcka** [comment]
Sure, here is the image I tested(one of th tif channels) and segmenation mask where each new cell instance has a unique ID.
[example_data.zip](https://github.com/user-attachments/files/16355620/example_data.zip)

The code I use for extracting features is: 

nyx = Nyxus(["*ALL*"])
features = nyx.featurize_files(
    ["/Channel_25_image" 
    ], 
    ["/Channel_25_mask"
    ],
	False)

**Comment by mikemcka** [comment]
I concluded yesterday after looking at another dataset with much more background intensity visually and with nyxus that the negative cells are showing up as having positive signal because of the background signal being present. I asked my supervisor about it too and they mentioned that the stain of the tissue wasnt ideal for that channel, so that makes sense. As for the rows containing nan values this is just because function cannot calculate a feature value with no data. Still not quite sure what is going on with the GABOR columns.

**Comment by mikemcka** [comment]
here is a sample example region of the data with the poor staining leading to high background if you were interested:
![image](https://github.com/user-attachments/assets/f9c8002b-0c55-4710-bc83-7eb67d474a03)

**Comment by friskluft** [comment]
Hi Mike,
Nyxus developer here.

First, thanks for the feedback on our software, for the detailed feedback, and for an interesting sample of data.

Most of the cases where you are getting NAN or INF feature values are due to zero pixel intensity range within a region of interest (ROI). I intercept such values replacing them with "0.0" only in the command line version of Nyxus to provide stability of bulk data processing pipelines. The Python API version was designed with the interactive scenario in mind so it reports NANs and INFs for user awareness. I can produce a NAN/INF-free output in the Python version, too, if you find it necessary for your work.

The Gabor feature results in INF due to the fact that the baseline filter response used as a denominator to the filter bank response is all zeroes, in turn, due to default parameters of Gabor feature precalibrated for dense (mostly nonzero) ROI images, while your ROIs are actually highly sparse nonzero pixel clouds. Such sparse pixel clouds don't have low-frequency spectrum components so the application of a Gabor filter bank to extract features from a raw (that is, not interpolated via a simplicial complex or some other way) sparse pixel cloud ROI image is doubtful. We can discuss this problem further and try to calibrate filter bank parameters if you find extracting valid Gabor features from such sparse data necessary.

Cheers,
=Andriy

**Comment by mikemcka** [comment]
Hi Andriy,

Thanks for getting back to me so quickly.

That was the conclusion I came to as well, and returning nan values for the pyhton API makes sense, I would suggest leaving it as it is because if features like GABOR which cannot be calculated with sparse cloud pixel datasets like mine would lead to complications if you didnt have the background understanding as to why the Gabor was returning 0 for all cells and they assumed that that the function was working correctly and they included the values rather than excluding the GABOR columns. It could be a good idea to add to the docs that GABOR doesnt work for sparse pixel cloud datasets like mine to help them troubleshoot.

For now I think its fine if I just exclude those columns, nyxus has generated many other features of interest for me to try training models with for now. 

Many thanks for all the help and the quick reply. Nyxus is a great tool and my coworkers and I are very greatful for all the hard work.

Cheers,

Mike
