### ISSUE TITLE
Multichannel Pyramidal OMETIFF feature extraction

### ISSUE THREAD

**Issue by rjesud** [PolusAI/nyxus#41]
Does Nyxus support feature extraction from multichannel pyramidal ometiff files? or do the channels need to be saved as seperate files?

Related, does Nyxus support feature extraction on numpy, dask or zarr arrays?

Thanks!

**Comment by sameeul** [comment]
At the moment, processing multi-channel data requires the channels to be saved as separate OMETiff files. However, we plan to support multi-channel images in the future. How difficult for you would it be to save your data as separate channel images?

Nyxus can read image files in OMEZarr format. Regarding Numpy and Dask arrays, let us clarify: do you mean feeding in-memory image data from the Python side to Nyxus instead of reading them from the file system?

**Comment by sameeul** [comment]
At the moment, we don't support images defined as Numpy and Dask arrays, but can consider adding their support.
Meanwhile, we recommend you using OMETiff format. Resource-wise, Nyxus is optimized to read OMETiff images.

**Comment by sameeul** [comment]
Also, we are curious about what kind of use cases you plan to use Nyxus for.

**Comment by rjesud** [comment]
@sameeul Thank you for your response. We are interested in single-cell feature calculation from multiplex digital pathology whole slide images. Depending on the staining and imaging platform, one can have upwards of 12 channels. Tissues can have upwards of 1 million single-cell regions. At a minimum, for every cell we would extract the mean fluorescent intensity across all channels. This would ultimatley become a cell-by-expression matrix which can be used for downstream cell-type clustering.

**Comment by hsidky** [comment]
@rjesud Sounds like Nyxus is pretty well suited for your analysis. As a fairly new library, we're actively working on new features, improved functionality, and better documentation. We're very interested in your feedback as you use Nyxus. If you would like to discussing anything in more detail, feel free to reach out to me at hythem.sidky@nih.gov. 

Thanks!
